site_name: vecs
site_url: https://supabase.github.io/vecs
site_description: Vector Database Client for pgvector

repo_name: supabase/vecs
repo_url: https://github.com/supabase/vecs

theme:
    name: 'readthedocs'
    features:
      - navigation.expand
    palette:
        primary: grey
        accent: red
nav:
  - Introduction: index.md
  - Guides:
    - API: api.md
    - Hosting: hosting.md
  - Concepts:
    - Collections: concepts_collections.md
    - Adapters: concepts_adapters.md
    - Indexes: concepts_indexes.md
    - Metadata: concepts_metadata.md
  - Integrations:
    - OpenAI: integrations_openai.md
    - Bedrock: integrations_amazon_bedrock.md
    - HuggingFace Inference Endpoints: integrations_huggingface_inference_endpoints.md
  - Support:
    - Changelog: support_changelog.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
